INSERT INTO items (title,description,thumbnail_photo_url,price,color,date_posted,available,year,make,model)
VALUES ('Honda civic 2022','The 2022 Honda Civic is one of the bestselling and best-known compact cars on the planet. Emerging now in sedan and hatchback body styles, it’s offered as a Civic LX, Sport, EX, or Touring.', 'http://canadianautoreview.ca/images/car_photos/2022-honda-civic-sedan-touring/civic-800.jpg', 20000, 'white', '2022-06-29 20:23:32', true, 2022, 'Honda', 'civic'),

('Mercedes c class 2021','The Mercedes-Benz C-Class is available in sedan, coupe and convertible body styles, the C-Class is a versatile small luxury car that offers an appealing mix of comfort, performance and top-notch construction.', 'https://images.pistonheads.com/nimg/43794/20C0673_091.jpg', 30000, 'silver', '2022-06-28 20:23:32', true, 2021, 'Mercedes-Benz','C-class'),

('Mercedes S class 2020','The 2020 Mercedes-Benz S-class has long been a shining example of what luxury should be, largely due to its sumptuous looks and impressive performance. Whether you choose the spacious sedan, dignified coupe, or lavish convertible, these top-shelf Benzes are chock full with the latest technology and the finest of materials', 'https://www.carjunction.com/car_images2/78633_90606/90606a_578x417.jpg', 40000, 'black', '2022-06-24 20:23:32', true, 2020, 'Mercedes-Benz', 'S-class'),

('Mercedes GLC 2021','Passenger space and cargo volume can make or break an SUV, and luxurious, powerful models like the Mercedes-Benz GLC are certainly no exceptions. Thankfully, the Mercedes-Benz GLC dimensions are just one more area in which this segment leader excels. If you''re ready to conquer your to-dos in Phoenix and Gilbert, then look no further. We''ve covered everything you''ll need to know below, so you can move forward with confidence.', 'https://di-uploads-pod7.dealerinspire.com/mercedesbenzofgreenwichredesign/uploads/2020/11/Red-GLC.png', 50000, 'red', '2022-06-22 20:23:32', true, 2020, 'Mercedec-Benz','GLC-class'),

('Mercedes G class 2022','When it comes to off-road capability and luxury pedigree, the 2022 Mercedes-Benz G-class is in a class of its own. Also known as the Geländewagen, it''s essentially a Ford Bronco or Jeep Wrangler for the rich and famous.', 'https://s1.cdn.autoevolution.com/images-webp/news/2022-mercedes-benz-g-class-goes-live-at-iaa-2021-in-professional-line-guise-168739-7.jpg.webp', 23000, 'orange', '2022-06-19 20:23:32', true, 2022, 'Mercedes-Benz','G-class'),

('Mercedes A class 2022','Mercedes-Benz once struggled to produce affordable entry-level cars that still felt luxurious, but it''s now closer to getting that formula right. The A-Class is the smallest and most affordable sedan in the Mercedes lineup and impresses with its on-brand styling and admirable acceleration, even with the base engine.', 'https://s3.us-east-2.amazonaws.com/dealer-inspire-vps-vehicle-images/28003886/W1K3F4HB6NJ337627/bcf31231aa54802542f11566cb1fec39.jpg', 80000, 'white', '2022-06-12 20:23:32', true, 2022, 'Mercedec-Benz','A-class'),

('Mercedes GLE 2020','Get acquainted with the newly reimagined 2020 GLE. Looking toward the future of progress, this SUV sets innovation into motion. Equipped with the all-new Mercedes-Benz User Experience system (MBUX), your desires are met through artificial intelligence as it learns your preferences along the way. Optional augmented reality enhances navigation, illuminating your path with groundbreaking features.', 'https://nafta.starconnect-ce.i.mercedes-benz.com/iris/iris.png?COSY-EU-100-1713d0VXqrEFqtyO67PobzIr3eWsrrCsdRRzwQZ6kIZbMw3SGtlaMtsd2HdcUfp8qXGEubSJ0l3IrOB2NW2bApjtwI5ux5YQC30CQkzNBm6m7j86ZhKViKh%25vq4r%25yLRgY2Yax%255hrH1GBfn8w0hyoiZKbYM4FvSlTg9LYT6PDarDSeWHnUtsd8B3cUfiA1XGEWymJ0ld%25xOB2zB5bAp7oMIkbX1ZxhpTg9vvO6PDK1ASeWgwWtsdR5jcUfG%25yXGE0GwJ0lBHtOB2A85bAp5kwI5uCmDQC3zkpkze94pOy1qFm9eUP0L1NTmj32vvRWydVXjdhcfWF0FT3THuPsa28uKxvB7BseWA4PdY&&BKGND=9&IMGT=P27&POV=be040%2Cpzm&crop=0,0,1920,1150&width=2880&height=1725', 90000, 'blue', '2022-05-29 20:23:32', true, 2022, 'Mercedec-Benz','GLE-Class'),

('Mercedes CLS 2020','The CLS-class is a study in contradictions, but one thing that''s clear is its commitment to luxury and performance. It has four doors, yet Mercedes markets it as a coupe (you can thank its fastback styling for that choice). It''s a large car, yet it has a small trunk.', 'https://di-uploads-pod7.dealerinspire.com/mercedesbenzburlingtonca/uploads/2020/03/gls-2020.jpg', 39000, 'silver', '2022-06-25 20:23:32', true, 2022, 'Mercedec-Benz','CLS-class');
