-- Drop and recreate Users table (Example)
-- npm run db:reset => run on terminal
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS items CASCADE;



CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,

  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  thumbnail_photo_url TEXT NOT NULL,
  price INTEGER NOT NULL DEFAULT 0,
  color VARCHAR(255) NOT NULL,
  date_posted TIMESTAMP NOT NULL,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  year INTEGER NOT NULL,
  make VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL

);

CREATE TABLE favorites (
  id SERIAL PRIMARY KEY NOT NULL,

  item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE messages (
  id SERIAL PRIMARY KEY NOT NULL,

  sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  receiver_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,

  message VARCHAR(255) NOT NULL,
  message_data_time TIMESTAMP WITHOUT TIME ZONE NOT NULL

);


